# Copyright Sierra
# Workflow tasks: 25 seeds + 75 variations (3 rounds) = 100 total

from tau_bench.types import Action, Task
from tau_bench.envs.workflow.tasks import TASKS as SEEDS

R1 = [
    # V1-0 (P1: query→aggregate→report→email pipeline)
    Task(user_id="EMP008", instruction="Your email is betty.anderson99@company.com. Query all sales data for the East region. Aggregate by product, summing quantities. Generate a summary report titled 'East Region Product Volume'. Email it to william.lee58@company.com with subject 'East Sales Volume'. What product has the highest quantity?",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "betty.anderson99@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP008"}), Action(name="query_sales_data", kwargs={"region": "East"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "quantity", "operation": "sum"})], outputs=[]),
    # V1-1 (P1: query→filter→aggregate→report→email)
    Task(user_id="EMP017", instruction="You are Jessica Johnson, EMP017. Query all sales. Filter to amount greater than 10000. Aggregate by customer_id, summing amounts. Generate a detailed report titled 'Top Customer Spending'. Email to your manager. How many customers spent over $10,000 total?",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP017"}), Action(name="query_sales_data", kwargs={}), Action(name="filter_data", kwargs={"data_ref": "latest_query", "field": "amount", "operator": "greater_than", "value": "10000"}), Action(name="aggregate_data", kwargs={"data_ref": "81e4133662ea", "group_by": "customer_id", "metric": "amount", "operation": "sum"})], outputs=[]),
    # V1-2 (P1: query→aggregate→format table→email)
    Task(user_id="EMP016", instruction="Your email is richard.jones77@company.com. Query sales for product 'Widget A'. Aggregate by region, averaging amounts. Format as a table. Email the table to emily.harris67@company.com subject 'Widget A Regional Performance'. Which region has the highest average?",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "richard.jones77@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP016"}), Action(name="query_sales_data", kwargs={"product": "Widget A"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "region", "metric": "amount", "operation": "avg"})], outputs=[]),
    # V1-3 (P2: project→find blocked→create tasks)
    Task(user_id="EMP008", instruction="You are Betty Anderson, EMP008. Check project PRJ007 for blocked tasks. For each, create a follow-up task assigned to yourself titled 'Resolve: [original]', priority high, due 2024-11-22. How many blocked tasks?",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP008"}), Action(name="get_project_details", kwargs={"project_id": "PRJ007"})], outputs=[]),
    # V1-4 (P2: list projects→summarize→email)
    Task(user_id="EMP019", instruction="Your email is emily.harris67@company.com. List all your projects. For each, get details and count tasks by status. Generate a report 'My Projects Overview'. Email to yourself. Which project has the most todo tasks?",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "emily.harris67@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP019"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP019"}), Action(name="get_project_details", kwargs={"project_id": "PRJ001"}), Action(name="get_project_details", kwargs={"project_id": "PRJ004"}), Action(name="get_project_details", kwargs={"project_id": "PRJ005"}), Action(name="get_project_details", kwargs={"project_id": "PRJ017"})], outputs=[]),
    # V1-5 (P2: project budget alert)
    Task(user_id="EMP009", instruction="You are William Lee, EMP009 (Finance). Check project PRJ005 budget. Calculate percentage spent. If over 70%, generate a 'Budget Warning' report and email to the project owner. Tell me the exact percentage and remaining budget.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP009"}), Action(name="get_project_details", kwargs={"project_id": "PRJ005"})], outputs=[]),
    # V1-6 (P3: HR+project multi-source)
    Task(user_id="EMP014", instruction="You are Michelle Martin, EMP014 (HR). Check HR records for EMP021 and EMP040. Also check which projects they're on. For anyone with rating below 4.0, send them a message about scheduling a performance improvement meeting.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP014"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP021"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP040"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP021"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP040"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP021"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP040"})], outputs=[]),
    # V1-7 (P3: calendar+project conflict check)
    Task(user_id="EMP011", instruction="Your email is susan.white28@company.com. Check calendar for Nov 20 (Wednesday). Also check project PRJ002 for tasks assigned to you due this week. List all meetings and critical tasks. Any conflicts?",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "susan.white28@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP011"}), Action(name="get_calendar", kwargs={"employee_id": "EMP011", "date": "2024-11-20"}), Action(name="get_project_details", kwargs={"project_id": "PRJ002"})], outputs=[]),
    # V1-8 (P3: files+sales→compose email)
    Task(user_id="EMP009", instruction="You are William Lee, EMP009 (Finance). Search for Finance department files. Also query sales for the Central region. Aggregate sales by product, summing amounts. Compose an email to linda.king47@company.com about regional budget allocation referencing the data.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP009"}), Action(name="search_files", kwargs={"department": "Finance"}), Action(name="query_sales_data", kwargs={"region": "Central"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "amount", "operation": "sum"})], outputs=[]),
    # V1-9 (P4: query→threshold→branch)
    Task(user_id="EMP016", instruction="You are Richard Jones, EMP016. Query sales for the West region. Aggregate by sales_rep, summing amounts. If any rep has under $5000, create a task on PRJ013 'Coach: [rep name]', priority medium, due 2024-11-29. How many reps need coaching?",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP016"}), Action(name="query_sales_data", kwargs={"region": "West"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "sales_rep", "metric": "amount", "operation": "sum"})], outputs=[]),
    # V1-10 (P4: HR conditional)
    Task(user_id="EMP007", instruction="You are Joseph Lewis, EMP007 (HR). Check HR record for EMP016. If performance rating is 4.0+ and last review was over 60 days ago, create a task on PRJ016 'Schedule review for EMP016'. If rating < 4.0, message them about a development plan.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP007"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP016"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP016"})], outputs=[]),
    # V1-11 (P5: scan project→update statuses)
    Task(user_id="EMP013", instruction="You are Jennifer Lewis, EMP013. In project PRJ003, find all 'todo' tasks assigned to you. Update each to 'in_progress'. Send a message to the project owner confirming you've started work.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP013"}), Action(name="get_project_details", kwargs={"project_id": "PRJ003"})], outputs=[]),
    # V1-12 (P5: weekly status)
    Task(user_id="EMP011", instruction="Your email is susan.white28@company.com. Create a weekly status for project PRJ012. Get details, count tasks by status, calculate completion percentage. Generate report titled 'PRJ012 Weekly - Nov 15'. Email to yourself.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "susan.white28@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP011"}), Action(name="get_project_details", kwargs={"project_id": "PRJ012"})], outputs=[]),
    # V1-13 (P6: full analyst workflow)
    Task(user_id="EMP017", instruction="You are Jessica Johnson, EMP017 (Finance). Full analysis: (1) Query November sales (date_from 2024-11-01, date_to 2024-11-15). (2) Aggregate by region, summing amounts. (3) Generate a detailed report 'November Sales by Region'. (4) Email to betty.anderson99@company.com subject 'Nov Sales Analysis'. Total November sales?",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP017"}), Action(name="query_sales_data", kwargs={"date_from": "2024-11-01", "date_to": "2024-11-15"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "region", "metric": "amount", "operation": "sum"}), Action(name="generate_report", kwargs={"title": "November Sales by Region", "data_ref": "2123fe685590", "format": "detailed", "author_id": "EMP017"})], outputs=[]),
    # V1-14 (P6: cross-source dashboard)
    Task(user_id="EMP019", instruction="Your email is emily.harris67@company.com. Build a dashboard: (1) Get PRJ001 status. (2) Query sales for your department. (3) Check your calendar Nov 18. (4) Get HR record. Compile into report 'Weekly Dashboard - Emily Harris'. Email to yourself.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "emily.harris67@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP019"}), Action(name="get_project_details", kwargs={"project_id": "PRJ001"}), Action(name="query_sales_data", kwargs={}), Action(name="get_calendar", kwargs={"employee_id": "EMP019", "date": "2024-11-18"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP019"})], outputs=[]),
    # V1-15 (policy: access other's HR)
    Task(user_id="EMP007", instruction="You are Joseph Lewis, EMP007 (HR). Check HR records for employees EMP030, EMP050, EMP070 in your department for annual review preparation.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP007"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP030"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP050"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP070"})], outputs=[]),
    # V1-16 (policy: email confirmation)
    Task(user_id="EMP006", instruction="You are Linda King, EMP006 (Product). Get project PRJ009 details. Compose an email to all members about the upcoming milestone. Subject: 'Milestone Update: [project name]'. List the members and get confirmation before sending.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP006"}), Action(name="get_project_details", kwargs={"project_id": "PRJ009"})], outputs=[]),
    # V1-17 (policy: transfer out of scope)
    Task(user_id="EMP009", instruction="You are William Lee, EMP009 (Finance). You need to process a wire transfer of $500,000 to a vendor's international bank account. This requires treasury approval and compliance sign-off. If the system can't handle international wire transfers, transfer to treasury team.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP009"}), Action(name="transfer_to_human", kwargs={"summary": "Employee needs to process $500K international wire transfer. Requires treasury approval and compliance sign-off, outside scope of workflow automation."})], outputs=[]),
    # V1-18 (adversarial: wrong project)
    Task(user_id="EMP022", instruction="Your email is david.clark41@company.com. You want to check the 'Security Audit' project. You think it's PRJ001 but that's actually 'Q4 Product Launch'. Ask the agent to find your actual projects and the right one.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "david.clark41@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP022"}), Action(name="get_project_details", kwargs={"project_id": "PRJ001"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP022"})], outputs=[]),
    # V1-19 (adversarial: changes mind)
    Task(user_id="EMP018", instruction="You are David Harris, EMP018 (Design). You initially want to email a quick status update about PRJ020. But after checking the project details, you see there are critical blocked tasks. Instead, generate a formal 'Blocked Tasks Alert' report and email that.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP018"}), Action(name="get_project_details", kwargs={"project_id": "PRJ020"})], outputs=[]),
    # V1-20 (complex: full management workflow)
    Task(user_id="EMP016", instruction="You are Richard Jones, EMP016 (Operations). Weekly workflow: (1) Check PRJ019 for overdue tasks (due before Nov 15). (2) Query this week's sales for South region. (3) Aggregate by product. (4) Generate report 'Weekly Ops Summary'. (5) Email to your manager.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP016"}), Action(name="get_project_details", kwargs={"project_id": "PRJ019"}), Action(name="query_sales_data", kwargs={"region": "South", "date_from": "2024-11-11", "date_to": "2024-11-15"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "amount", "operation": "sum"})], outputs=[]),
    # V1-21 (complex: executive summary)
    Task(user_id="EMP008", instruction="Your email is betty.anderson99@company.com. Executive summary: (1) Query total sales by region for all time. (2) Get PRJ004 and PRJ008 status. (3) Check calendar Nov 19. (4) Generate report 'Finance Team Weekly Brief'. (5) Email to william.sanchez29@company.com.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "betty.anderson99@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP008"}), Action(name="query_sales_data", kwargs={}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "region", "metric": "amount", "operation": "sum"}), Action(name="get_project_details", kwargs={"project_id": "PRJ004"}), Action(name="get_project_details", kwargs={"project_id": "PRJ008"}), Action(name="get_calendar", kwargs={"employee_id": "EMP008", "date": "2024-11-19"})], outputs=[]),
    # V1-22 (complex: quarterly review)
    Task(user_id="EMP022", instruction="Your email is david.clark41@company.com. Prepare quarterly review: (1) Get your HR record. (2) List your projects. (3) Get details for each. (4) Query any sales you're involved in. Generate a self-review report.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "david.clark41@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP022"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP022"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP022"}), Action(name="get_project_details", kwargs={"project_id": "PRJ007"}), Action(name="get_project_details", kwargs={"project_id": "PRJ009"})], outputs=[]),
    # V1-23 (complex: incident response)
    Task(user_id="EMP013", instruction="You are Jennifer Lewis, EMP013 (Engineering). PRJ003 has critical blocked tasks. (1) Get project details. (2) Create urgent task 'Incident: Unblock PRJ003', priority critical, due today. (3) Send message to project owner. (4) Generate incident report.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP013"}), Action(name="get_project_details", kwargs={"project_id": "PRJ003"}), Action(name="get_current_date", kwargs={})], outputs=[]),
    # V1-24 (complex: end-of-day wrap-up)
    Task(user_id="EMP019", instruction="You are Emily Harris, EMP019. End-of-day: (1) Check today's calendar. (2) Check your projects for tasks due today. (3) Update completed tasks. (4) Send daily summary to manager EMP001. (5) Generate daily log.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP019"}), Action(name="get_calendar", kwargs={"employee_id": "EMP019", "date": "2024-11-15"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP019"}), Action(name="get_project_details", kwargs={"project_id": "PRJ001"}), Action(name="get_project_details", kwargs={"project_id": "PRJ004"}), Action(name="get_project_details", kwargs={"project_id": "PRJ005"}), Action(name="get_project_details", kwargs={"project_id": "PRJ017"})], outputs=[]),
]

R2 = [
    Task(user_id="EMP004", instruction="You are William Sanchez, EMP004 (Product). Query sales for 'Pro Plan'. Aggregate by region, summing amounts. Generate report 'Pro Plan Regional Sales'. Email to joseph.lewis22@company.com. Top region?",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP004"}), Action(name="query_sales_data", kwargs={"product": "Pro Plan"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "region", "metric": "amount", "operation": "sum"})], outputs=[]),
    Task(user_id="EMP009", instruction="Your email is william.lee58@company.com. Query all sales. Filter amount > 20000. Aggregate by product, counting records. Generate table report 'Premium Deal Count'. Email to jessica.johnson20@company.com.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "william.lee58@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP009"}), Action(name="query_sales_data", kwargs={}), Action(name="filter_data", kwargs={"data_ref": "latest_query", "field": "amount", "operator": "greater_than", "value": "20000"})], outputs=[]),
    Task(user_id="EMP021", instruction="You are Joseph Williams, EMP021 (Engineering). Query sales for 'Service X'. Aggregate by sales_rep, summing amounts. Format as table. Email to jennifer.lewis90@company.com subject 'Service X Rep Performance'.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP021"}), Action(name="query_sales_data", kwargs={"product": "Service X"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "sales_rep", "metric": "amount", "operation": "sum"})], outputs=[]),
    Task(user_id="EMP006", instruction="Your email is linda.king47@company.com. Check PRJ011. Find all tasks with priority 'critical'. For each, create follow-up 'Escalate: [title]', priority critical, due 2024-11-20, assigned to the original assignee.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "linda.king47@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP006"}), Action(name="get_project_details", kwargs={"project_id": "PRJ011"})], outputs=[]),
    Task(user_id="EMP017", instruction="You are Jessica Johnson, EMP017. List your projects. Get details for each. Which project has the highest budget? Which has spent the most? Email a summary to betty.anderson99@company.com.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP017"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP017"}), Action(name="get_project_details", kwargs={"project_id": "PRJ002"}), Action(name="get_project_details", kwargs={"project_id": "PRJ005"}), Action(name="get_project_details", kwargs={"project_id": "PRJ014"})], outputs=[]),
    Task(user_id="EMP002", instruction="Your email is omar.williams13@company.com. Check PRJ019. Calculate budget utilization (spent/budget * 100). If over 90%, generate 'Critical Budget Alert' report and email to the project owner.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "omar.williams13@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP002"}), Action(name="get_project_details", kwargs={"project_id": "PRJ019"})], outputs=[]),
    Task(user_id="EMP007", instruction="You are Joseph Lewis, EMP007 (HR). Check HR records for EMP011, EMP013, EMP018. Identify anyone with performance_rating >= 4.5. Send them a congratulations message. List who qualifies.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP007"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP011"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP013"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP018"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP011"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP013"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP018"})], outputs=[]),
    Task(user_id="EMP004", instruction="You are William Sanchez, EMP004. Check your calendar Nov 19 (Tuesday). Also check PRJ015 for tasks due this week assigned to you. List meetings and tasks. Any scheduling pressure?",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP004"}), Action(name="get_calendar", kwargs={"employee_id": "EMP004", "date": "2024-11-19"}), Action(name="get_project_details", kwargs={"project_id": "PRJ015"})], outputs=[]),
    Task(user_id="EMP014", instruction="Your email is michelle.martin97@company.com. Search HR department files. Also query sales for the North region. Compose an email to richard.jones77@company.com about headcount planning referencing the data.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "michelle.martin97@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP014"}), Action(name="search_files", kwargs={"department": "HR"}), Action(name="query_sales_data", kwargs={"region": "North"})], outputs=[]),
    Task(user_id="EMP018", instruction="You are David Harris, EMP018. Query Central region sales. Aggregate by product, counting records. If any product has fewer than 3 sales, create task on PRJ020 'Boost sales: [product]' priority high, due 2024-11-30.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP018"}), Action(name="query_sales_data", kwargs={"region": "Central"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "amount", "operation": "count"})], outputs=[]),
    Task(user_id="EMP014", instruction="You are Michelle Martin, EMP014 (HR). Check HR record for EMP022. If rating < 3.5, create task on PRJ006 'Development plan for EMP022'. If >= 3.5, send them a message about their upcoming review.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP014"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP022"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP022"})], outputs=[]),
    Task(user_id="EMP021", instruction="You are Joseph Williams, EMP021. In PRJ006, find all 'in_progress' tasks with > 25 hours logged. Update them to 'done'. Message each assignee confirming completion.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP021"}), Action(name="get_project_details", kwargs={"project_id": "PRJ006"})], outputs=[]),
    Task(user_id="EMP006", instruction="Your email is linda.king47@company.com. Create weekly status for PRJ009. Count tasks by status. Calculate total hours logged. Generate report 'PRJ009 Sprint Review'. Email to all members.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "linda.king47@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP006"}), Action(name="get_project_details", kwargs={"project_id": "PRJ009"})], outputs=[]),
    Task(user_id="EMP009", instruction="You are William Lee, EMP009 (Finance). Full Q4 analysis: (1) Query October sales (10-01 to 10-31). (2) Aggregate by product, summing amounts. (3) Generate 'Q4 October Product Sales' report. (4) Email to jessica.johnson20@company.com.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP009"}), Action(name="query_sales_data", kwargs={"date_from": "2024-10-01", "date_to": "2024-10-31"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "amount", "operation": "sum"})], outputs=[]),
    Task(user_id="EMP016", instruction="Your email is richard.jones77@company.com. Dashboard: (1) Get PRJ013 and PRJ020 status. (2) Query sales for Operations dept. (3) Calendar Nov 20. (4) HR record. Compile report 'Ops Dashboard'. Email to yourself.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "richard.jones77@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP016"}), Action(name="get_project_details", kwargs={"project_id": "PRJ013"}), Action(name="get_project_details", kwargs={"project_id": "PRJ020"}), Action(name="query_sales_data", kwargs={}), Action(name="get_calendar", kwargs={"employee_id": "EMP016", "date": "2024-11-20"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP016"})], outputs=[]),
    Task(user_id="EMP004", instruction="You are William Sanchez, EMP004. Check HR records for EMP025 and EMP035 for your annual review. Compare their ratings.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP004"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP025"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP035"})], outputs=[]),
    Task(user_id="EMP021", instruction="You are Joseph Williams, EMP021. Get PRJ006 details. Compose email to all project members about the next deadline. Subject: 'Deadline Alert: [project name]'. Confirm before sending.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP021"}), Action(name="get_project_details", kwargs={"project_id": "PRJ006"})], outputs=[]),
    Task(user_id="EMP014", instruction="You are Michelle Martin, EMP014 (HR). You need to conduct a formal disciplinary hearing. This requires union representation and legal counsel. If outside scope, transfer to HR legal team.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP014"}), Action(name="transfer_to_human", kwargs={"summary": "Employee needs to conduct disciplinary hearing requiring union representation and legal counsel. Outside scope of workflow automation."})], outputs=[]),
    Task(user_id="EMP011", instruction="Your email is susan.white28@company.com. You want the 'Brand Campaign' project. You think it's PRJ010 but that's 'Mobile App v2'. Ask agent to find the right project from your list.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "susan.white28@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP011"}), Action(name="get_project_details", kwargs={"project_id": "PRJ010"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP011"})], outputs=[]),
    Task(user_id="EMP002", instruction="You are Omar Williams, EMP002 (Support). You want to send a quick status email about PRJ019. After checking, you find many overdue tasks. Generate a formal 'Overdue Tasks Report' instead.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP002"}), Action(name="get_project_details", kwargs={"project_id": "PRJ019"})], outputs=[]),
    Task(user_id="EMP013", instruction="You are Jennifer Lewis, EMP013. Full workflow: (1) Check PRJ003 blocked tasks. (2) Query recent sales. (3) Aggregate by region. (4) Generate 'Engineering Ops Report'. (5) Email to project owner.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP013"}), Action(name="get_project_details", kwargs={"project_id": "PRJ003"}), Action(name="query_sales_data", kwargs={"date_from": "2024-11-01", "date_to": "2024-11-15"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "region", "metric": "amount", "operation": "sum"})], outputs=[]),
    Task(user_id="EMP004", instruction="Your email is william.sanchez29@company.com. Executive brief: (1) Query all sales by product. (2) Get PRJ015 status. (3) Calendar Nov 21. (4) Generate 'Product Team Brief'. (5) Email to linda.king47@company.com.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "william.sanchez29@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP004"}), Action(name="query_sales_data", kwargs={}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "amount", "operation": "sum"}), Action(name="get_project_details", kwargs={"project_id": "PRJ015"}), Action(name="get_calendar", kwargs={"employee_id": "EMP004", "date": "2024-11-21"})], outputs=[]),
    Task(user_id="EMP018", instruction="Your email is david.harris43@company.com. Quarterly review: (1) HR record. (2) List projects. (3) Check calendar this week. Generate 'Q4 Self-Review - David Harris'.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "david.harris43@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP018"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP018"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP018"}), Action(name="get_project_details", kwargs={"project_id": "PRJ013"}), Action(name="get_project_details", kwargs={"project_id": "PRJ020"})], outputs=[]),
    Task(user_id="EMP006", instruction="You are Linda King, EMP006 (Product). PRJ009 has urgent blocked tasks. (1) Get details. (2) Create 'Incident: PRJ009 blocked' task, critical, due today. (3) Message the project owner. (4) Generate incident report.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP006"}), Action(name="get_project_details", kwargs={"project_id": "PRJ009"}), Action(name="get_current_date", kwargs={})], outputs=[]),
    Task(user_id="EMP017", instruction="You are Jessica Johnson, EMP017. End-of-day: (1) Today's calendar. (2) Your projects' tasks due today. (3) Send summary to manager EMP008. (4) Generate daily log.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP017"}), Action(name="get_calendar", kwargs={"employee_id": "EMP017", "date": "2024-11-15"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP017"}), Action(name="get_project_details", kwargs={"project_id": "PRJ002"}), Action(name="get_project_details", kwargs={"project_id": "PRJ005"}), Action(name="get_project_details", kwargs={"project_id": "PRJ014"})], outputs=[]),
]

R3 = [
    Task(user_id="EMP011", instruction="You are Susan White, EMP011 (Design). Query sales for 'Service Y'. Aggregate by region, summing quantities. Generate report 'Service Y Distribution'. Email to david.harris43@company.com.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP011"}), Action(name="query_sales_data", kwargs={"product": "Service Y"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "region", "metric": "quantity", "operation": "sum"})], outputs=[]),
    Task(user_id="EMP013", instruction="Your email is jennifer.lewis90@company.com. Query all sales. Filter quantity > 50. Aggregate by region, summing amounts. Report 'High Volume Sales'. Email to emily.harris67@company.com.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "jennifer.lewis90@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP013"}), Action(name="query_sales_data", kwargs={}), Action(name="filter_data", kwargs={"data_ref": "latest_query", "field": "quantity", "operator": "greater_than", "value": "50"})], outputs=[]),
    Task(user_id="EMP002", instruction="You are Omar Williams, EMP002 (Support). Query sales for 'Basic Plan'. Aggregate by customer_id, counting records. Format as table. Email to nancy.robinson44@company.com subject 'Basic Plan Customer Activity'.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP002"}), Action(name="query_sales_data", kwargs={"product": "Basic Plan"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "customer_id", "metric": "record_id", "operation": "count"})], outputs=[]),
    Task(user_id="EMP019", instruction="Your email is emily.harris67@company.com. Check PRJ017 for tasks with 'blocked' status. Create follow-up tasks 'Unblock: [title]' for each, priority high, due Nov 25.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "emily.harris67@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP019"}), Action(name="get_project_details", kwargs={"project_id": "PRJ017"})], outputs=[]),
    Task(user_id="EMP022", instruction="You are David Clark, EMP022. List your projects. Get details for each. Generate 'Portfolio Summary - David Clark'. Email to yourself. Which project is closest to deadline?",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP022"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP022"}), Action(name="get_project_details", kwargs={"project_id": "PRJ007"}), Action(name="get_project_details", kwargs={"project_id": "PRJ009"})], outputs=[]),
    Task(user_id="EMP013", instruction="You are Jennifer Lewis, EMP013 (Engineering). Check PRJ003 budget. Calculate remaining. If under 20% remaining, generate 'Budget Critical' report and email to the project owner. What's the exact remaining %?",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP013"}), Action(name="get_project_details", kwargs={"project_id": "PRJ003"})], outputs=[]),
    Task(user_id="EMP009", instruction="Your email is william.lee58@company.com. Check HR for EMP017 and EMP008. Find who has higher rating. Message the lower-rated one about development opportunities.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "william.lee58@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP009"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP017"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP008"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP017"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP008"})], outputs=[]),
    Task(user_id="EMP016", instruction="You are Richard Jones, EMP016. Calendar Nov 21 (Thursday). Also check PRJ013 for your tasks due this week. Any time pressure? List meetings and deadlines.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP016"}), Action(name="get_calendar", kwargs={"employee_id": "EMP016", "date": "2024-11-21"}), Action(name="get_project_details", kwargs={"project_id": "PRJ013"})], outputs=[]),
    Task(user_id="EMP008", instruction="Your email is betty.anderson99@company.com. Search Finance files. Also query all sales. Aggregate by region, averaging amounts. Compose email to william.lee58@company.com about quarterly budget allocation.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "betty.anderson99@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP008"}), Action(name="search_files", kwargs={"department": "Finance"}), Action(name="query_sales_data", kwargs={}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "region", "metric": "amount", "operation": "avg"})], outputs=[]),
    Task(user_id="EMP011", instruction="You are Susan White, EMP011 (Design). Query East region sales. Aggregate by product, summing quantities. If any product has < 5 total quantity, create task on PRJ002 'Promote: [product]', medium priority, due Nov 30.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP011"}), Action(name="query_sales_data", kwargs={"region": "East"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "quantity", "operation": "sum"})], outputs=[]),
    Task(user_id="EMP007", instruction="Your email is joseph.lewis22@company.com. Check HR for EMP004. If rating >= 4.0 and salary_band is L4 or below, create task 'Promotion review for EMP004' on PRJ016. If already L5+, just send a congrats message.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "joseph.lewis22@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP007"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP004"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP004"})], outputs=[]),
    Task(user_id="EMP004", instruction="You are William Sanchez, EMP004. PRJ015 has tasks. Find all 'done' tasks. Calculate total hours logged for done tasks. Send a summary message to each assignee thanking them.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP004"}), Action(name="get_project_details", kwargs={"project_id": "PRJ015"})], outputs=[]),
    Task(user_id="EMP022", instruction="Your email is david.clark41@company.com. Weekly status for PRJ007. Count tasks by status. Hours logged total. Generate 'PRJ007 Weekly Report'. Email to project owner.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "david.clark41@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP022"}), Action(name="get_project_details", kwargs={"project_id": "PRJ007"})], outputs=[]),
    Task(user_id="EMP008", instruction="You are Betty Anderson, EMP008. Full analysis: (1) Query September sales (09-01 to 09-30). (2) Aggregate by product, summing amounts. (3) Generate 'Q3 September Sales' report. (4) Email to your manager.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP008"}), Action(name="query_sales_data", kwargs={"date_from": "2024-09-01", "date_to": "2024-09-30"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "amount", "operation": "sum"})], outputs=[]),
    Task(user_id="EMP007", instruction="Your email is joseph.lewis22@company.com. HR dashboard: (1) Check HR records for EMP006, EMP009, EMP014. (2) List departments. (3) Search HR files. (4) Generate 'HR Monthly Review' report. (5) Email to michelle.martin97@company.com.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "joseph.lewis22@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP007"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP006"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP009"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP014"}), Action(name="list_departments", kwargs={}), Action(name="search_files", kwargs={"department": "HR"})], outputs=[]),
    Task(user_id="EMP017", instruction="You are Jessica Johnson, EMP017. Check HR records for EMP011 and EMP019 for team review.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP017"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP011"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP019"})], outputs=[]),
    Task(user_id="EMP040", instruction="You are Nancy Robinson, EMP040 (Product). Get PRJ006 details. Email all members about a design review meeting. Subject: 'Design Review: [project name]'. Confirm first.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP040"}), Action(name="get_project_details", kwargs={"project_id": "PRJ006"})], outputs=[]),
    Task(user_id="EMP022", instruction="You are David Clark, EMP022 (Support). You need to escalate a customer complaint to the executive team with legal implications. Transfer to executive support.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP022"}), Action(name="transfer_to_human", kwargs={"summary": "Customer complaint with legal implications needs executive escalation. Outside scope of workflow automation."})], outputs=[]),
    Task(user_id="EMP017", instruction="Your email is jessica.johnson20@company.com. Looking for 'Annual Report' project. Think it's PRJ007 but that's 'Security Audit'. Find the right one from your projects.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "jessica.johnson20@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP017"}), Action(name="get_project_details", kwargs={"project_id": "PRJ007"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP017"})], outputs=[]),
    Task(user_id="EMP016", instruction="You are Richard Jones, EMP016. Want to send quick update about PRJ020. After checking, many tasks are behind. Generate 'PRJ020 Risk Assessment' report instead and email to manager.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP016"}), Action(name="get_project_details", kwargs={"project_id": "PRJ020"})], outputs=[]),
    Task(user_id="EMP018", instruction="You are David Harris, EMP018. Full workflow: (1) PRJ013 blocked tasks. (2) PRJ020 overdue tasks. (3) Query recent sales. (4) Aggregate. (5) Report 'Design Team Ops'. (6) Email to richard.jones77@company.com.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP018"}), Action(name="get_project_details", kwargs={"project_id": "PRJ013"}), Action(name="get_project_details", kwargs={"project_id": "PRJ020"}), Action(name="query_sales_data", kwargs={"date_from": "2024-11-08", "date_to": "2024-11-15"}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "product", "metric": "amount", "operation": "sum"})], outputs=[]),
    Task(user_id="EMP009", instruction="Your email is william.lee58@company.com. Brief: (1) All sales by region. (2) PRJ005, PRJ011 status. (3) Calendar Nov 22. (4) Report 'Finance Weekly'. (5) Email to betty.anderson99@company.com.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "william.lee58@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP009"}), Action(name="query_sales_data", kwargs={}), Action(name="aggregate_data", kwargs={"data_ref": "latest_query", "group_by": "region", "metric": "amount", "operation": "sum"}), Action(name="get_project_details", kwargs={"project_id": "PRJ005"}), Action(name="get_project_details", kwargs={"project_id": "PRJ011"}), Action(name="get_calendar", kwargs={"employee_id": "EMP009", "date": "2024-11-22"})], outputs=[]),
    Task(user_id="EMP002", instruction="Your email is omar.williams13@company.com. Self-review: (1) HR record. (2) List projects. (3) Get details. Generate 'Self-Assessment - Omar Williams'.",
        actions=[Action(name="find_employee_by_email", kwargs={"email": "omar.williams13@company.com"}), Action(name="get_employee_details", kwargs={"employee_id": "EMP002"}), Action(name="get_hr_record", kwargs={"employee_id": "EMP002"}), Action(name="list_employee_projects", kwargs={"employee_id": "EMP002"}), Action(name="get_project_details", kwargs={"project_id": "PRJ019"})], outputs=[]),
    Task(user_id="EMP021", instruction="You are Joseph Williams, EMP021 (Engineering). PRJ006 has critical issues. (1) Get details. (2) Create 'Incident: PRJ006 at risk' task, critical, due today. (3) Message owner. (4) Generate incident report.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP021"}), Action(name="get_project_details", kwargs={"project_id": "PRJ006"}), Action(name="get_current_date", kwargs={})], outputs=[]),
    Task(user_id="EMP008", instruction="You are Betty Anderson, EMP008 (Finance). End-of-day: (1) Today's calendar. (2) Project tasks due today for PRJ004, PRJ007, PRJ008. (3) Daily summary to manager. (4) Daily log.",
        actions=[Action(name="get_employee_details", kwargs={"employee_id": "EMP008"}), Action(name="get_calendar", kwargs={"employee_id": "EMP008", "date": "2024-11-15"}), Action(name="get_project_details", kwargs={"project_id": "PRJ004"}), Action(name="get_project_details", kwargs={"project_id": "PRJ007"}), Action(name="get_project_details", kwargs={"project_id": "PRJ008"})], outputs=[]),
]

TASKS = SEEDS + R1 + R2 + R3
