# Copyright Sierra
# Healthcare tasks: 25 seeds + 75 variations (3 rounds × 25) = 100 total

from tau_bench.types import Action, Task
from tau_bench.envs.healthcare.tasks import TASKS as SEEDS

# Round 1: 25 variations using fresh patients
R1 = [
    # V1-0 (F1: insurance calc, premium)
    Task(user_id="P10035", instruction="Your email is james.williams78@email.com. Premium plan, $1500 deductible met. You want to book a Neurology Consultation (PROC011). Search Neurology Oct 1. Calculate your exact cost. Pay with HSA ($2000 balance).",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "james.williams78@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10035"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC011"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10035"}), Action(name="search_specialists", kwargs={"department": "Neurology", "date": "2024-10-01"})], outputs=[]),
    # V1-1 (F1: basic plan, partial deductible)
    Task(user_id="P10087", instruction="You are Ashley Robinson, born 2003-09-21. Basic plan, $2000 deductible already met. Book a Cardiology Consultation (PROC003, no referral for it). Check if you need a referral first. If you don't have one, just check the cost anyway. What would the out-of-pocket be?",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Ashley", "last_name": "Robinson", "dob": "2003-09-21"}), Action(name="get_patient_details", kwargs={"patient_id": "P10087"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC003"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10087"})], outputs=[]),
    # V1-2 (F1: HSA + CC split)
    Task(user_id="P10109", instruction="Your email is wei.harris70@email.com. Standard plan, $200 deductible met. You have Echocardiogram appointment APT00099 ($120). Your HSA has $1500. Will HSA cover it all or need credit card too?",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "wei.harris70@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10109"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00099"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10109"})], outputs=[]),
    # V1-3 (F1: compare costs)
    Task(user_id="P10146", instruction="You are Christopher Scott, born 2004-02-14. Standard plan, $0 deductible met. You have 2 Echocardiogram appointments (APT00076 and APT00160). Check both. Calculate your total cost for both combined.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Christopher", "last_name": "Scott", "dob": "2004-02-14"}), Action(name="get_patient_details", kwargs={"patient_id": "P10146"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00076"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00160"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10146"})], outputs=[]),
    # V1-4 (F1: total cost across multiple)
    Task(user_id="P10137", instruction="Your email is chen.baker59@inbox.com. Standard plan, $2000 deductible met. Check all 3 scheduled appointments. Calculate total out-of-pocket for all of them.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "chen.baker59@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10137"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00086"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00233"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00335"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10137"})], outputs=[]),
    # V1-5 (F2: search + pick earliest)
    Task(user_id="P10107", instruction="You are Nancy Clark, born 1987-07-14. Premium plan. Book a Stress Test (PROC005). Search Cardiology specialists Oct 8. Pick earliest slot. Pay credit card 3168.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Nancy", "last_name": "Clark", "dob": "1987-07-14"}), Action(name="get_patient_details", kwargs={"patient_id": "P10107"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC005"}), Action(name="search_specialists", kwargs={"department": "Cardiology", "date": "2024-10-08"})], outputs=[]),
    # V1-6 (F2: compare specialists across dates)
    Task(user_id="P10140", instruction="Your email is thomas.nelson19@email.com. Need an EEG Test (PROC012, referral REF_P10140_PROC012). Compare Neurology availability Oct 5 vs Oct 6. Book whichever has the earliest morning slot. Pay HSA.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "thomas.nelson19@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10140"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC012"}), Action(name="search_specialists", kwargs={"department": "Neurology", "date": "2024-10-05"}), Action(name="search_specialists", kwargs={"department": "Neurology", "date": "2024-10-06"})], outputs=[]),
    # V1-7 (F2: search by department + find procedure)
    Task(user_id="P10092", instruction="You are David Scott, born 1959-03-18. Want an Orthopedics procedure but not MRI. Search Orthopedics procedures. Pick Physical Therapy (PROC008, referral REF_P10092_PROC008). Search specialists Oct 7.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "David", "last_name": "Scott", "dob": "1959-03-18"}), Action(name="get_patient_details", kwargs={"patient_id": "P10092"}), Action(name="search_procedures", kwargs={"department": "Orthopedics"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC008"}), Action(name="search_specialists", kwargs={"department": "Orthopedics", "date": "2024-10-07"})], outputs=[]),
    # V1-8 (F3: scan + cancel without referral)
    Task(user_id="P10183", instruction="Your email is anthony.white85@email.com. Check all 4 scheduled appointments. Some need referrals. Cancel any that require a referral but you don't have one. Tell me which.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "anthony.white85@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10183"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00038"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00212"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00271"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC007"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC004"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC019"})], outputs=[]),
    # V1-9 (F3: scan + find expensive)
    Task(user_id="P10109", instruction="You are Wei Harris, born 2005-11-04. Check all 3 scheduled appointments. Which one costs the most? If any costs over $100, consider cancelling it. Tell me the costs.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Wei", "last_name": "Harris", "dob": "2005-11-04"}), Action(name="get_patient_details", kwargs={"patient_id": "P10109"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00099"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00207"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00263"})], outputs=[]),
    # V1-10 (F3: scan + cancel most expensive)
    Task(user_id="P10129", instruction="Your email is james.johnson57@email.com. Budget is tight. Check all scheduled appointments. Cancel the most expensive one. What's the remaining total?",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "james.johnson57@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10129"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00164"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00336"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00336", "reason": "over budget"})], outputs=["224"],
    ),
    # V1-11 (F4: cancel + rebook different specialist)
    Task(user_id="P10101", instruction="You are Anthony Adams, born 1997-03-09. Cancel LASIK Consultation APT00307 (Oct 8). Rebook same procedure with a different Ophthalmology specialist on Oct 12. Pay with HSA.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Anthony", "last_name": "Adams", "dob": "1997-03-09"}), Action(name="get_patient_details", kwargs={"patient_id": "P10101"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00307"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00307", "reason": "rescheduling"}), Action(name="search_specialists", kwargs={"department": "Ophthalmology", "date": "2024-10-12"})], outputs=[]),
    # V1-12 (F4: cancel + rebook different procedure)
    Task(user_id="P10172", instruction="Your email is mei.nguyen95@email.com. Cancel Echocardiogram APT00155 ($224). Instead book a cheaper Cardiology Consultation (PROC003, referral REF_P10172_PROC003). Search Cardiology Oct 1. How much do you save?",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "mei.nguyen95@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10172"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00155"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00155", "reason": "switching to consultation first"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC003"}), Action(name="search_specialists", kwargs={"department": "Cardiology", "date": "2024-10-01"})], outputs=[]),
    # V1-13 (F4: cancel + rebook + recalculate)
    Task(user_id="P10166", instruction="You are Brian Martin, born 1968-01-03. Cancel Neurology Consultation APT00370 ($164). Rebook as a Hearing Test (PROC017, no referral needed) instead. Search ENT Oct 15. Calculate new cost. Basic plan, $2000 deductible met. Pay HSA.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Brian", "last_name": "Martin", "dob": "1968-01-03"}), Action(name="get_patient_details", kwargs={"patient_id": "P10166"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00370"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00370", "reason": "switching procedure"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC017"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10166"}), Action(name="search_specialists", kwargs={"department": "ENT", "date": "2024-10-15"})], outputs=[]),
    # V1-14 (F5: reschedule + change procedure)
    Task(user_id="P10141", instruction="Your email is james.lewis24@email.com. For APT00297 (Physical Therapy, Oct 6), change the procedure to MRI (PROC007, referral REF_P10141_PROC007). Also reschedule to Oct 10 with a different specialist. Pay credit card 7172.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "james.lewis24@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10141"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00297"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC007"}), Action(name="search_specialists", kwargs={"department": "Orthopedics", "date": "2024-10-10"}), Action(name="modify_appointment_procedure", kwargs={"appointment_id": "APT00297", "new_procedure_id": "PROC007", "payment_method": "cc_P10141_3893"})], outputs=[]),
    # V1-15 (F5: reschedule different date + specialist)
    Task(user_id="P10131", instruction="You are Mark Anderson, born 1955-10-02. Reschedule APT00120 (Neurology Consultation, Oct 4) to Oct 8. Want a different neurologist. Search Oct 8 for morning slots.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Mark", "last_name": "Anderson", "dob": "1955-10-02"}), Action(name="get_patient_details", kwargs={"patient_id": "P10131"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00120"}), Action(name="search_specialists", kwargs={"department": "Neurology", "date": "2024-10-08"})], outputs=[]),
    # V1-16 (F5: change procedure + recalculate)
    Task(user_id="P10136", instruction="Your email is karen.taylor64@mail.com. For APT00011 (Echocardiogram, $59), change to Stress Test (PROC005) instead. Premium plan, $0 deductible met. What's the new cost? Pay credit card 1385.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "karen.taylor64@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10136"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00011"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC005"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10136"}), Action(name="modify_appointment_procedure", kwargs={"appointment_id": "APT00011", "new_procedure_id": "PROC005", "payment_method": "cc_P10136_4129"})], outputs=[]),
    # V1-17 (POL: referral check)
    Task(user_id="P10139", instruction="You are Daniel Thompson, born 1990-12-28. You want a Colonoscopy (PROC013). You have referral REF_P10139_PROC013. Search Gastroenterology Oct 10. Book first slot. Pay credit card 7727.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Daniel", "last_name": "Thompson", "dob": "1990-12-28"}), Action(name="get_patient_details", kwargs={"patient_id": "P10139"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC013"}), Action(name="search_specialists", kwargs={"department": "Gastroenterology", "date": "2024-10-10"})], outputs=[]),
    # V1-18 (POL: cancel fee)
    Task(user_id="P10043", instruction="Your email is noah.campbell48@mail.com. Premium plan. Cancel APT00360 (Cardiology, Sep 27, less than 2 weeks away). Premium gets free cancellation. Confirm no fee.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "noah.campbell48@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10043"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00360"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00360", "reason": "schedule change"})], outputs=[]),
    # V1-19 (POL: premium free cancel)
    Task(user_id="P10053", instruction="You are Lucas Jones, born 1991-02-18. Premium plan. Cancel APT00077 (Hearing Test, Sep 23). Confirm free cancellation for premium.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Lucas", "last_name": "Jones", "dob": "1991-02-18"}), Action(name="get_patient_details", kwargs={"patient_id": "P10053"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00077"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00077", "reason": "no longer needed"})], outputs=[]),
    # V1-20 (ADV: wrong date)
    Task(user_id="P10092", instruction="Your email is david.scott35@email.com. You have a colonoscopy but think it's Oct 10. Actually it might be a different date. Ask agent to check all your appointments and find the colonoscopy.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "david.scott35@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10092"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00154"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00249"})], outputs=[]),
    # V1-21 (COMP: premium gets HSA credit)
    Task(user_id="P10035", instruction="You are James Williams, born 1998-11-14. Premium plan. Your past LASIK Consultation (APT00267, completed) had a 3-hour wait. Want $50 compensation to HSA.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "James", "last_name": "Williams", "dob": "1998-11-14"}), Action(name="get_patient_details", kwargs={"patient_id": "P10035"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00267"}), Action(name="add_hsa_credit", kwargs={"patient_id": "P10035", "amount": 50})], outputs=["50"]),
    # V1-22 (COMP: basic → transfer)
    Task(user_id="P10087", instruction="Your email is ashley.robinson71@inbox.com. Basic plan. Past appointment was terrible. Want compensation. If can't help basic plan, transfer me.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "ashley.robinson71@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10087"}), Action(name="transfer_to_human_agents", kwargs={"summary": "Basic plan patient requesting compensation. Must transfer per policy."})], outputs=[]),
    # V1-23 (dependent booking)
    Task(user_id="P10042", instruction="You are William Nguyen, born 1974-01-07. Book a Well-Child Visit (PROC019) for your child (check dependents). Search Pediatrics Oct 8. Book earliest. Pay HSA.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "William", "last_name": "Nguyen", "dob": "1974-01-07"}), Action(name="get_patient_details", kwargs={"patient_id": "P10042"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC019"}), Action(name="search_specialists", kwargs={"department": "Pediatrics", "date": "2024-10-08"})], outputs=[]),
    # V1-24 (complex end-to-end)
    Task(user_id="P10107", instruction="Your email is nancy.clark24@email.com. Premium, $800 deductible met. Check all 3 appointments. Cancel APT00397 (Sinus Surgery Consultation). Instead search for a Dermatology Consultation (PROC010, no referral) on Oct 10. Calculate new cost. Pay with HSA ($200) and credit card 3168 for rest.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "nancy.clark24@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10107"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00041"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00328"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00397"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00397", "reason": "switching to dermatology"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC010"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10107"}), Action(name="search_specialists", kwargs={"department": "Dermatology", "date": "2024-10-10"})], outputs=[]),
]

# Round 2 and 3 follow the same pattern with different patients
# (abbreviated for space - same structure, different data)
R2 = [
    Task(user_id="P10000", instruction="You are Elizabeth Robinson, born 1994-08-17. Premium, $2000 deductible met. Check APT00119 (Colonoscopy $129) and APT00311 (Neurology $44). Calculate total out-of-pocket. Pay with HSA.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Elizabeth", "last_name": "Robinson", "dob": "1994-08-17"}), Action(name="get_patient_details", kwargs={"patient_id": "P10000"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00119"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00311"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10000"})], outputs=[]),
    Task(user_id="P10195", instruction="Your email is barbara.rivera90@mail.com. Basic plan, $1500 deductible met. EEG Test APT00050 ($264). HSA has $2000. Will HSA cover it? Calculate exact cost.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "barbara.rivera90@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10195"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00050"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10195"})], outputs=[]),
    Task(user_id="P10191", instruction="You are Steven Martinez, born 1964-12-21. Premium, $1500 deductible met. Check both appointments. Calculate per-appointment and total cost.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Steven", "last_name": "Martinez", "dob": "1964-12-21"}), Action(name="get_patient_details", kwargs={"patient_id": "P10191"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00092"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00156"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10191"})], outputs=[]),
    Task(user_id="P10142", instruction="Your email is lucas.baker95@email.com. Standard, $1000 deductible met. Compare cost of Dermatology Consultation (PROC010, $200) vs Hearing Test (PROC017, $150). Which costs you less? Calculate both.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "lucas.baker95@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10142"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC010"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC017"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10142"})], outputs=[]),
    Task(user_id="P10101", instruction="You are Anthony Adams, born 1997-03-09. Premium, $500 deductible met. Check all 3 scheduled appointments. Total cost across all?",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Anthony", "last_name": "Adams", "dob": "1997-03-09"}), Action(name="get_patient_details", kwargs={"patient_id": "P10101"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00274"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00307"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00346"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10101"})], outputs=[]),
    Task(user_id="P10153", instruction="Your email is mark.kim59@mail.com. Premium, $800 deductible met. Book a Skin Cancer Screening (PROC009). Search Dermatology Oct 5. Earliest slot. Pay credit card 7228.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "mark.kim59@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10153"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC009"}), Action(name="search_specialists", kwargs={"department": "Dermatology", "date": "2024-10-05"})], outputs=[]),
    Task(user_id="P10166", instruction="You are Brian Martin, born 1968-01-03. Need Neurology Consultation (PROC011, referral REF_P10166_PROC011). Compare availability Oct 12 vs Oct 13. Book earliest morning slot. Pay HSA.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Brian", "last_name": "Martin", "dob": "1968-01-03"}), Action(name="get_patient_details", kwargs={"patient_id": "P10166"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC011"}), Action(name="search_specialists", kwargs={"department": "Neurology", "date": "2024-10-12"}), Action(name="search_specialists", kwargs={"department": "Neurology", "date": "2024-10-13"})], outputs=[]),
    Task(user_id="P10137", instruction="Your email is chen.baker59@inbox.com. Want a Cardiology procedure but not sure which. Search Cardiology department procedures. You have referral for PROC003. Search specialists Oct 8.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "chen.baker59@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10137"}), Action(name="search_procedures", kwargs={"department": "Cardiology"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC003"}), Action(name="search_specialists", kwargs={"department": "Cardiology", "date": "2024-10-08"})], outputs=[]),
    Task(user_id="P10146", instruction="You are Christopher Scott, born 2004-02-14. Check all 3 appointments. Which ones require referrals? Do you have the referrals? Cancel any that need a referral you don't have.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Christopher", "last_name": "Scott", "dob": "2004-02-14"}), Action(name="get_patient_details", kwargs={"patient_id": "P10146"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00040"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00076"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00160"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC010"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC004"})], outputs=[]),
    Task(user_id="P10195", instruction="Your email is barbara.rivera90@mail.com. Check both appointments. For any over $200, find if same department has a cheaper alternative procedure. Tell me options.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "barbara.rivera90@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10195"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00050"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00135"}), Action(name="search_procedures", kwargs={"department": "Neurology"})], outputs=[]),
    Task(user_id="P10092", instruction="You are David Scott, born 1959-03-18. You have 2 Colonoscopy appointments. Cancel the later one (APT00249). Keep the earlier one (APT00154). What's the remaining cost?",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "David", "last_name": "Scott", "dob": "1959-03-18"}), Action(name="get_patient_details", kwargs={"patient_id": "P10092"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00154"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00249"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00249", "reason": "duplicate"})], outputs=["260"]),
    Task(user_id="P10135", instruction="Your email is joseph.adams19@inbox.com. Cancel APT00176 (Echocardiogram Oct 8). Rebook same procedure Oct 15 with different specialist. Pay HSA.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "joseph.adams19@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10135"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00176"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00176", "reason": "rescheduling"}), Action(name="search_specialists", kwargs={"department": "Cardiology", "date": "2024-10-15"})], outputs=[]),
    Task(user_id="P10142", instruction="You are Lucas Baker, born 1991-01-15. Cancel APT00276 (Dermatology $60). Book Eye Exam (PROC015, no referral) instead. Search Ophthalmology Oct 5. Cheaper? Pay credit card 8044.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Lucas", "last_name": "Baker", "dob": "1991-01-15"}), Action(name="get_patient_details", kwargs={"patient_id": "P10142"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00276"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00276", "reason": "switching"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC015"}), Action(name="search_specialists", kwargs={"department": "Ophthalmology", "date": "2024-10-05"})], outputs=[]),
    Task(user_id="P10140", instruction="Your email is thomas.nelson19@email.com. Cancel Stress Test APT00096 ($170). Rebook as Knee X-Ray (PROC006, no referral). Search Orthopedics Oct 15. Calculate new cost. Standard plan, $200 deductible met.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "thomas.nelson19@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10140"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00096"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00096", "reason": "switching to X-ray"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC006"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10140"}), Action(name="search_specialists", kwargs={"department": "Orthopedics", "date": "2024-10-15"})], outputs=[]),
    Task(user_id="P10169", instruction="You are Jennifer Jackson, born 1965-10-16. For APT00095 (Echocardiogram Oct 11), change to Stress Test (PROC005). Reschedule to Oct 13. Search Cardiology Oct 13. Premium plan. What's the cost difference?",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Jennifer", "last_name": "Jackson", "dob": "1965-10-16"}), Action(name="get_patient_details", kwargs={"patient_id": "P10169"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00095"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC005"}), Action(name="search_specialists", kwargs={"department": "Cardiology", "date": "2024-10-13"}), Action(name="modify_appointment_procedure", kwargs={"appointment_id": "APT00095", "new_procedure_id": "PROC005", "payment_method": "cc_P10169_2086"})], outputs=[]),
    Task(user_id="P10191", instruction="Your email is steven.martinez10@mail.com. Reschedule APT00156 (Neurology Sep 22) to Oct 5. Want morning slot with different neurologist. Search Oct 5.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "steven.martinez10@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10191"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00156"}), Action(name="search_specialists", kwargs={"department": "Neurology", "date": "2024-10-05"})], outputs=[]),
    Task(user_id="P10153", instruction="You are Mark Kim, born 1983-08-05. For APT00144 (Skin Cancer Screening, $27), change to Dermatology Consultation (PROC010, $200). Premium, $800 deductible met. What's the new cost? Credit card 7228.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Mark", "last_name": "Kim", "dob": "1983-08-05"}), Action(name="get_patient_details", kwargs={"patient_id": "P10153"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00144"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC010"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10153"}), Action(name="modify_appointment_procedure", kwargs={"appointment_id": "APT00144", "new_procedure_id": "PROC010", "payment_method": "cc_P10153_7299"})], outputs=[]),
    Task(user_id="P10092", instruction="Your email is david.scott35@email.com. Book Physical Therapy (PROC008, referral REF_P10092_PROC008). Search Orthopedics Oct 9. First available. Pay HSA.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "david.scott35@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10092"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC008"}), Action(name="search_specialists", kwargs={"department": "Orthopedics", "date": "2024-10-09"})], outputs=[]),
    Task(user_id="P10026", instruction="You are Mary Anderson, born 2002-05-24. Premium, $500 deductible met. Cancel APT00125 (Colonoscopy Oct 9). More than 48h away. Premium = free cancel. Confirm.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Mary", "last_name": "Anderson", "dob": "2002-05-24"}), Action(name="get_patient_details", kwargs={"patient_id": "P10026"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00125"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00125", "reason": "not needed"})], outputs=[]),
    Task(user_id="P10017", instruction="Your email is david.torres49@email.com. Premium. Cancel APT00361 (Psychiatric Eval Sep 20). Less than a week away. Premium gets free cancellation.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "david.torres49@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10017"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00361"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00361", "reason": "schedule conflict"})], outputs=[]),
    Task(user_id="P10139", instruction="You are Daniel Thompson, born 1990-12-28. Have a Hearing Test but think it's on Sep 20. It's actually Sep 22. Ask agent to find all your appointments.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Daniel", "last_name": "Thompson", "dob": "1990-12-28"}), Action(name="get_patient_details", kwargs={"patient_id": "P10139"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00363"})], outputs=[]),
    Task(user_id="P10101", instruction="Your email is anthony.adams72@mail.com. Premium. Past Dermatology appointment (APT00123, completed) had 2-hour wait. Want $50 HSA credit.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "anthony.adams72@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10101"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00123"}), Action(name="add_hsa_credit", kwargs={"patient_id": "P10101", "amount": 50})], outputs=["50"]),
    Task(user_id="P10129", instruction="You are James Johnson, born 1994-01-28. Basic plan. Past appointment was awful. Want compensation. If can't help, transfer.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "James", "last_name": "Johnson", "dob": "1994-01-28"}), Action(name="get_patient_details", kwargs={"patient_id": "P10129"}), Action(name="transfer_to_human_agents", kwargs={"summary": "Basic plan patient requesting compensation. Must transfer per policy."})], outputs=[]),
    Task(user_id="P10030", instruction="Your email is emma.perez55@email.com. Book a Well-Child Visit (PROC019) for your child (check dependents). Search Pediatrics Oct 6. Book earliest. Pay credit card 9807.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "emma.perez55@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10030"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC019"}), Action(name="search_specialists", kwargs={"department": "Pediatrics", "date": "2024-10-06"})], outputs=[]),
    Task(user_id="P10109", instruction="You are Wei Harris, born 2005-11-04. Standard, $200 deductible met. Check all 3 appointments. Cancel APT00263 (GI Consultation). Search for Eye Exam (PROC015) on Oct 3 instead. Calculate new cost. Pay with HSA first, credit card for rest.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Wei", "last_name": "Harris", "dob": "2005-11-04"}), Action(name="get_patient_details", kwargs={"patient_id": "P10109"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00099"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00207"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00263"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00263", "reason": "switching to eye exam"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC015"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10109"}), Action(name="search_specialists", kwargs={"department": "Ophthalmology", "date": "2024-10-03"})], outputs=[]),
]

# Round 3 uses same patients but different tasks/combos
R3 = [
    Task(user_id="P10131", instruction="Your email is mark.anderson16@mail.com. Premium, $800 deductible met. Want to compare: GI Consultation (PROC014, $250) vs Dermatology Consultation (PROC010, $200). Calculate out-of-pocket for each. Which is cheaper?",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "mark.anderson16@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10131"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC014"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC010"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10131"})], outputs=[]),
    Task(user_id="P10183", instruction="You are Anthony White, born 1996-06-07. Basic, $0 deductible met. You have 4 appointments totaling a lot. Calculate total cost across all. What if you cancel the most expensive? New total?",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Anthony", "last_name": "White", "dob": "1996-06-07"}), Action(name="get_patient_details", kwargs={"patient_id": "P10183"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00038"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00212"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00271"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10183"})], outputs=[]),
    Task(user_id="P10043", instruction="Your email is noah.campbell48@mail.com. Premium, $1500 deductible met. Check both appointments. HSA has $200. Is HSA enough for both? If not, how much on credit card?",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "noah.campbell48@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10043"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00136"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00360"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10043"})], outputs=[]),
    Task(user_id="P10169", instruction="You are Jennifer Jackson, born 1965-10-16. Premium, $1500 deductible met. Both appointments: Echocardiogram ($59) and Stress Test ($84). Compare costs. Tell me per-appointment breakdown.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Jennifer", "last_name": "Jackson", "dob": "1965-10-16"}), Action(name="get_patient_details", kwargs={"patient_id": "P10169"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00095"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00281"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10169"})], outputs=[]),
    Task(user_id="P10172", instruction="Your email is mei.nguyen95@email.com. Basic, $800 deductible met. Check Cardiology Consultation APT00039 ($144) and Echocardiogram APT00155 ($224). Total out-of-pocket?",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "mei.nguyen95@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10172"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00039"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00155"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10172"})], outputs=[]),
    Task(user_id="P10136", instruction="You are Karen Taylor, born 1989-11-04. Premium, $0 deductible. Book Physical Therapy (PROC008, referral REF_P10136_PROC008). Search Orthopedics Oct 10. Earliest afternoon slot. Pay credit card.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Karen", "last_name": "Taylor", "dob": "1989-11-04"}), Action(name="get_patient_details", kwargs={"patient_id": "P10136"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC008"}), Action(name="search_specialists", kwargs={"department": "Orthopedics", "date": "2024-10-10"})], outputs=[]),
    Task(user_id="P10129", instruction="Your email is james.johnson57@email.com. Need Sinus Surgery Consultation (PROC018, referral REF_P10129_PROC018). Search ENT Oct 8 and Oct 9. Pick the day with earlier availability.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "james.johnson57@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10129"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC018"}), Action(name="search_specialists", kwargs={"department": "ENT", "date": "2024-10-08"}), Action(name="search_specialists", kwargs={"department": "ENT", "date": "2024-10-09"})], outputs=[]),
    Task(user_id="P10101", instruction="You are Anthony Adams, born 1997-03-09. Search all departments. You want something related to eyes. Search Ophthalmology procedures. Check if LASIK Consultation needs a referral. You have referral for PROC020 only.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Anthony", "last_name": "Adams", "dob": "1997-03-09"}), Action(name="get_patient_details", kwargs={"patient_id": "P10101"}), Action(name="list_departments", kwargs={}), Action(name="search_procedures", kwargs={"department": "Ophthalmology"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC016"})], outputs=[]),
    Task(user_id="P10137", instruction="Your email is chen.baker59@inbox.com. Check all 3 appointments. Cancel any Annual Physical Exams (PROC001) since you just had one last month. Keep everything else.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "chen.baker59@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10137"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00086"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00233"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00335"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00233", "reason": "had physical recently"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00335", "reason": "had physical recently"})], outputs=[]),
    Task(user_id="P10107", instruction="You are Nancy Clark, born 1987-07-14. Premium. Check all appointments. For the most expensive one (APT00041, Stress Test $84), can you switch to a cheaper time? Search Cardiology Oct 12.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Nancy", "last_name": "Clark", "dob": "1987-07-14"}), Action(name="get_patient_details", kwargs={"patient_id": "P10107"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00041"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00328"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00397"}), Action(name="search_specialists", kwargs={"department": "Cardiology", "date": "2024-10-12"})], outputs=[]),
    Task(user_id="P10166", instruction="Your email is brian.martin43@inbox.com. Check Knee X-Ray APT00139 ($104) and Neurology APT00370 ($164). Total is $268. Cancel the more expensive one. Remaining?",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "brian.martin43@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10166"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00139"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00370"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00370", "reason": "too expensive"})], outputs=["104"]),
    Task(user_id="P10000", instruction="You are Elizabeth Robinson, born 1994-08-17. Cancel APT00311 (Neurology Sep 20). Rebook as Eye Exam (PROC015, no referral) Oct 5 instead. Search Ophthalmology. Pay HSA.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Elizabeth", "last_name": "Robinson", "dob": "1994-08-17"}), Action(name="get_patient_details", kwargs={"patient_id": "P10000"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00311", "reason": "switching to eye exam"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC015"}), Action(name="search_specialists", kwargs={"department": "Ophthalmology", "date": "2024-10-05"})], outputs=[]),
    Task(user_id="P10109", instruction="Your email is wei.harris70@email.com. Cancel GI Consultation APT00263 ($70). Rebook as Hearing Test (PROC017, no referral) Oct 8. Cheaper. Calculate savings. Pay HSA.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "wei.harris70@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10109"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00263", "reason": "switching to hearing test"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC017"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10109"}), Action(name="search_specialists", kwargs={"department": "ENT", "date": "2024-10-08"})], outputs=[]),
    Task(user_id="P10195", instruction="You are Barbara Rivera, born 1986-09-01. Cancel Annual Physical APT00135 ($84). Rebook as Blood Work (PROC002, no referral, $80) Oct 12. Search General Practice. Calculate new cost. Basic, $1500 deductible met. Pay HSA.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Barbara", "last_name": "Rivera", "dob": "1986-09-01"}), Action(name="get_patient_details", kwargs={"patient_id": "P10195"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00135", "reason": "switching to blood work"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC002"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10195"}), Action(name="search_specialists", kwargs={"department": "General Practice", "date": "2024-10-12"})], outputs=[]),
    Task(user_id="P10142", instruction="Your email is lucas.baker95@email.com. For APT00312 (Hearing Test Sep 30), change to Skin Cancer Screening (PROC009, no referral). Search Dermatology Oct 3. Standard, $1000 deductible met. Cost difference? CC 8044.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "lucas.baker95@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10142"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00312"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC009"}), Action(name="search_specialists", kwargs={"department": "Dermatology", "date": "2024-10-03"}), Action(name="modify_appointment_procedure", kwargs={"appointment_id": "APT00312", "new_procedure_id": "PROC009", "payment_method": "cc_P10142_7007"})], outputs=[]),
    Task(user_id="P10035", instruction="You are James Williams, born 1998-11-14. Reschedule APT00179 (Neurology Oct 1) to Oct 10. Search Neurology Oct 10. Pick afternoon slot.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "James", "last_name": "Williams", "dob": "1998-11-14"}), Action(name="get_patient_details", kwargs={"patient_id": "P10035"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00179"}), Action(name="search_specialists", kwargs={"department": "Neurology", "date": "2024-10-10"})], outputs=[]),
    Task(user_id="P10000", instruction="Your email is elizabeth.robinson50@inbox.com. For APT00119 (Colonoscopy, $129), change to GI Consultation (PROC014, $250 base but cheaper after insurance). Premium, $2000 deductible met. Compare costs. CC 1965.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "elizabeth.robinson50@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10000"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00119"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC014"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10000"}), Action(name="modify_appointment_procedure", kwargs={"appointment_id": "APT00119", "new_procedure_id": "PROC014", "payment_method": "cc_P10000_4808"})], outputs=[]),
    Task(user_id="P10146", instruction="You are Christopher Scott, born 2004-02-14. Standard, $0 deductible. Book Echocardiogram (PROC004). You don't have a referral. Check if you need one. If required and you don't have it, book a Cardiology Consultation (PROC003) first instead. Search Cardiology Oct 8.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Christopher", "last_name": "Scott", "dob": "2004-02-14"}), Action(name="get_patient_details", kwargs={"patient_id": "P10146"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC004"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC003"}), Action(name="search_specialists", kwargs={"department": "Cardiology", "date": "2024-10-08"})], outputs=[]),
    Task(user_id="P10135", instruction="Your email is joseph.adams19@inbox.com. Premium. Cancel APT00331 (Well-Child Visit Sep 16). Less than 24h away. Premium = free cancel. Confirm.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "joseph.adams19@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10135"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00331"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00331", "reason": "too soon"})], outputs=[]),
    Task(user_id="P10087", instruction="You are Ashley Robinson, born 2003-09-21. Basic plan. Cancel APT00075 (EEG Test Oct 2). More than 48h away. Basic plan without referral for EEG. What's the cancellation fee?",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Ashley", "last_name": "Robinson", "dob": "2003-09-21"}), Action(name="get_patient_details", kwargs={"patient_id": "P10087"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00075"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00075", "reason": "can't make it"})], outputs=[]),
    Task(user_id="P10140", instruction="Your email is thomas.nelson19@email.com. You think your LASIK appointment is Oct 1 but it's Sep 30. Ask agent to find it. Then check the details.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "thomas.nelson19@email.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10140"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00379"})], outputs=[]),
    Task(user_id="P10141", instruction="You are James Lewis, born 2004-12-26. Premium. Past Hearing Test (APT00057, completed) had terrible service - waited 90 minutes. Want $50 HSA credit. But you don't have HSA. Transfer to human instead.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "James", "last_name": "Lewis", "dob": "2004-12-26"}), Action(name="get_patient_details", kwargs={"patient_id": "P10141"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00057"}), Action(name="transfer_to_human_agents", kwargs={"summary": "Premium patient wants compensation but has no HSA account. Needs human assistance to determine alternative compensation method."})], outputs=[]),
    Task(user_id="P10166", instruction="Your email is brian.martin43@inbox.com. Basic plan. Bad experience at past appointment. Want compensation. If not eligible as basic, transfer.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "brian.martin43@inbox.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10166"}), Action(name="transfer_to_human_agents", kwargs={"summary": "Basic plan patient requesting compensation. Must transfer per policy."})], outputs=[]),
    Task(user_id="P10059", instruction="You are Elizabeth Jackson, born 1966-10-01. Book Well-Child Visit (PROC019) for your child (check dependents). Search Pediatrics Oct 9. Book earliest. Pay credit card 3551.",
        actions=[Action(name="find_patient_by_name_dob", kwargs={"first_name": "Elizabeth", "last_name": "Jackson", "dob": "1966-10-01"}), Action(name="get_patient_details", kwargs={"patient_id": "P10059"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC019"}), Action(name="search_specialists", kwargs={"department": "Pediatrics", "date": "2024-10-09"})], outputs=[]),
    Task(user_id="P10153", instruction="Your email is mark.kim59@mail.com. Premium, $800 deductible met. Check both appointments. Cancel APT00084 (Well-Child Visit). Search for Psychiatric Evaluation (PROC020, referral REF_P10153_PROC020) Oct 15 instead. Calculate cost. Pay credit card.",
        actions=[Action(name="find_patient_by_email", kwargs={"email": "mark.kim59@mail.com"}), Action(name="get_patient_details", kwargs={"patient_id": "P10153"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00084"}), Action(name="get_appointment_details", kwargs={"appointment_id": "APT00144"}), Action(name="cancel_appointment", kwargs={"appointment_id": "APT00084", "reason": "switching to psych eval"}), Action(name="get_procedure_details", kwargs={"procedure_id": "PROC020"}), Action(name="get_insurance_summary", kwargs={"patient_id": "P10153"}), Action(name="search_specialists", kwargs={"department": "Psychiatry", "date": "2024-10-15"})], outputs=[]),
]

TASKS = SEEDS + R1 + R2 + R3
